name: Build Medical Image Analysis software artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cmake
        uses: lukka/get-cmake@latest
        
      - name: Checkout the VTK repository
        run: |
          mkdir vtkbuildenv
          cd vtkbuildenv
          git clone https://gitlab.kitware.com/vtk/vtk.git
          cd vtk
          git checkout v9.0.3
          
      - name: Configure the VTK build
        run: >-
          cd vtkbuildenv &&
          mkdir build && cd build &&
          cmake -DCMAKE_INSTALL_PREFIX=/opt/vtk 
          -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib"
          -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE
          -DVTK_BUILD_ALL_MODULES_FOR_TESTS:BOOL=OFF
          -DBUILD_TESTING=OFF
          -DBUILD_EXAMPLES=OFF
          -DBUILD_DOCUMENTATION=OFF
          -DVTK_Group_Rendering:BOOL=OFF
          -DVTK_Group_StandAlone:BOOL=OFF
          -DVTK_Group_Qt=OFF
          -DVTK_Group_Imaging=ON
          -DVTK_Group_Views=ON
          -DModule_vtkRenderingFreeTypeFontConfig=OFF
          -DVTK_WRAP_PYTHON=ON
          -DVTK_PYTHON_VERSION=3
          -DPYTHON_EXECUTABLE=/usr/bin/python3
          -DVTK_USE_SYSTEM_LIBRARIES=ON
          -DVTK_USE_SYSTEM_LIBPROJ4=OFF
          -DVTK_USE_SYSTEM_GL2PS=OFF
          -DVTK_USE_SYSTEM_LIBHARU=OFF
          -DVTK_USE_SYSTEM_PUGIXML=OFF
          -DCMAKE_BUILD_TYPE=Release ../vtk
         
      - name: Build VTK
        run: cd vtkbuildenv/build && make -j 2 install
    
      - name: Checkout the ITK repository
        uses: actions/checkout@v2
        with:
          repository: InsightSoftwareConsortium/ITK
          ref: v4.13.3
          path: ITK4
      
      - name: Make the build directory for the ITK code
        run: mkdir itkbuildenv
        
      - name: Configure the ITK build
        run: |
          cd itkbuildenv
          cmake -DCMAKE_INSTALL_PREFIX=/opt/itk4 -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib" -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O3 -DNDEBUG" ../ITK4
          make -j 2 install
          
      - name: Prepare the archive
        run: |
          tar -cvf itk4.tar /opt/itk4
          
      - uses: actions/upload-artifact@v2
        with:
         name: itk4.tar
         path: itk4.tar
         

       
          
