name: Build Medical Image Analysis software artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cmake
        uses: lukka/get-cmake@latest
    
      - name: Checkout the ITK repository
        uses: actions/checkout@v2
        with:
          repository: InsightSoftwareConsortium/ITK
          ref: v4.13.3
          path: ITK4
      
      - name: Make the build directory for the ITK code
        run: mkdir itkbuildenv
        
      - name: Configure the ITK build
        run: |
          cd itkbuildenv
          cmake -DCMAKE_INSTALL_PREFIX=/opt/itk4 -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib" -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O3 -DNDEBUG" ../ITK4
          make -j 2 install
          
      - name: Prepare the archive
        run: |
          tar cvf itk4.tar /opt/itk4
          
      - uses: actions/upload-artifact@v2
        with:
         name: itk4
         path: itk4.tar
         
         
