name: Build Medical Image Analysis software artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cmake
        uses: lukka/get-cmake@latest
        
      - name: Checkout the VTK repository
        run: |
          mkdir vtkbuildenv
          cd vtkbuildenv
          git clone https://gitlab.kitware.com/vtk/vtk.git
          cd vtk
          git checkout v9.1.0          
          
      - name: Configure the VTK build
        run: >-
          cd vtkbuildenv &&
          mkdir build && cd build &&
          cmake 
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DBUILD_SHARED_LIBS:BOOL=OFF
          -DCMAKE_INSTALL_PREFIX=/opt/vtk 
          -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib"
          -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE
          -DVTK_BUILD_DOCUMENTATION=OFF
          -DVTK_BUILD_TESTING=OFF
          -DVTK_BUILD_EXAMPLES=OFF
          -DBUILD_USER_DEFINED_LIBS:BOOL=OFF
          -DVTK_LEGACY_REMOVE=ON         
          -DVTK_ANDROID_BUILD=OFF
          -DVTK_IOS_BUILD=OFF
          -DVTK_EXTRA_COMPILER_WARNINGS=OFF
          -DVTK_GROUP_ENABLE_Views=NO
          -DVTK_GROUP_ENABLE_Web=NO
          -DVTK_GROUP_ENABLE_Imaging=NO
          -DVTK_GROUP_ENABLE_Qt=DONT_WANT
          -DVTK_GROUP_ENABLE_Rendering=DONT_WANT
          -DVTK_PYTHON_VERSION=3
          -DVTK_ENABLE_WRAPPING=ON
          -DVTK_WRAP_PYTHON=ON
          -DVTK_WRAP_JAVA=OFF
          -DVTK_USE_LARGE_DATA=OFF
          ../vtk
         
      - name: Build VTK
        run: cd vtkbuildenv/build && make -j 2 install
        
      - name: Prepare the VTK archive
        run: |
          tar -cvf vtk.tar /opt/vtk
          
      - uses: actions/upload-artifact@v2
        with:
         name: vtk.tar
         path: vtk.tar
    
      - name: Checkout the ITK repository
        uses: actions/checkout@v2
        with:
          repository: InsightSoftwareConsortium/ITK
          ref: v4.13.3
          path: ITK4
      
      - name: Make the build directory for the ITK code
        run: mkdir itkbuildenv
        
      - name: Configure the ITK build
        run: |
          cd itkbuildenv
          cmake -DCMAKE_INSTALL_PREFIX=/opt/itk4 -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib" -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O3 -DNDEBUG" ../ITK4
          make -j 2 install
          
      - name: Prepare the archive
        run: |
          tar -cvf itk4.tar /opt/itk4
          
      - uses: actions/upload-artifact@v2
        with:
         name: itk4.tar
         path: itk4.tar
         
      - name: Checkout the ITK 5 repository
        uses: actions/checkout@v2
        with:
          repository: InsightSoftwareConsortium/ITK
          ref: v5.2.1
          path: ITK5
      
      - name: Make the build directory for the ITK 5 code
        run: mkdir itk5buildenv
        
      - name: Configure the ITK v5 build
        run: |
          cd itk5buildenv
          cmake -DCMAKE_INSTALL_PREFIX=/opt/itk5 -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib" -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_TESTING:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O3 -DNDEBUG" ../ITK5
          make -j 2 install
          
      - name: Prepare the archive
        run: |
          tar -cvf itk5.tar /opt/itk5
          
      - uses: actions/upload-artifact@v2
        with:
         name: itk5.tar
         path: itk5.tar
          

      - name: Checkout the NLopt repository
        run: |
          mkdir nloptenv
          cd nloptenv
          git clone -b v2.7.0 https://github.com/stevengj/nlopt nlopt
          
      - name: Configure, build and install the NLopt package
        run: |
          cd nloptenv
          mkdir nloptbuild
          cd nloptbuild
          cmake -DCMAKE_INSTALL_PREFIX=/opt/nlopt -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib" -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_SHARED_LIBS:STRING=OFF -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O3 -DNDEBUG" ../nlopt
          make -j 2 install
          
      - name: Prepare the NLOPT archive
        run: |
          tar -cvf nlopt.tar /opt/nlopt
 
      - uses: actions/upload-artifact@v2
        with:
          name: nlopt.tar
          path: nlopt.tar
